
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./(component)/Provider";
import AppContainer from "./(component)/AppContainer";
import Navigation from "./(component)/Navigation/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
    <Provider>
      <AppContainer>
        <Navigation />
        <main className="my-6">
        {children}
        </main>
      </AppContainer>
    </Provider>

      </body>
    </html>
  );
}
